import { Inter } from "next/font/google";
import "./globals.css";
import Header from '../partials/Header'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <html lang="pt-br">

        <body className={inter.className} style={{margin:'0px', padding:'0px'}}>
          <Header />
          {children}
        </body>
      </html>

    </>
  );
}